# Generated by Django 3.0.8 on 2020-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='address',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='contact',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='dob',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='user_type',
            field=models.CharField(choices=[('admins', 'admins'), ('teacher', 'teacher'), ('student', 'student')], default=None, max_length=20, null=True),
        ),
    ]
