# Generated by Django 3.0.7 on 2020-08-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_auto_20200731_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='images',
            field=models.URLField(default=None, null=True),
        ),
    ]
